-- MySQL Workbench Synchronization
-- Generated: 2023-03-14 11:36
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: angel

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `idUSUARIO` INT(11) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Mail` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUSUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`TAREAS` (
  `idTAREAS` INT(11) NOT NULL,
  `H_Inicio` DATETIME NOT NULL,
  `H_Fin` DATETIME NOT NULL,
  `Nombre_Tarea` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `USUARIO_idUSUARIO` INT(11) NOT NULL,
  `Observaciones` VARCHAR(45) NULL DEFAULT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTAREAS`, `USUARIO_idUSUARIO`),
  INDEX `fk_TAREAS_USUARIO_idx` (`USUARIO_idUSUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_TAREAS_USUARIO`
    FOREIGN KEY (`USUARIO_idUSUARIO`)
    REFERENCES `mydb`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
